load("@rules_shar//:macros.bzl", sh_binary = "shar_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_binary(
    name = "binary",
    srcs = [
        "binary.bash",
    ],
    deps = [
        "//example/lib:lib",
    ],
)

sh_test(
    name = "test",
    srcs = [
        ":test.bash",
    ],
    args = [
        "$(location :binary_shar)",
    ],
    data = [
        ":binary_shar",
    ],
    size = "small",
)
